name: Static Website application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- uses: chrislennon/action-aws-cli@v1.1

    
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3
    - name: S3 update
      run: |
        aws s3 rm s3://amran-online-cv/index.html
        aws s3 cp index.html s3://amran-online-cv/index.html
    - name: Cloudfront Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.Cloudfront }} --paths "/index.html"
